### ISSUE TITLE
Prefixes and suffixes

### ISSUE THREAD

**Issue by danieltabrizian** [thekeenant/Tabbed#6]
I dont know for sure but can you implement the suffix and prefix feature to increase tablist entry lenght to 4-something?

**Comment by thekeenant** [comment]
It seems to support lengths up to what you want without prefix+suffix. Originally I had that implemented, but noticed the 16 length maximum didn't seem to be there anymore.

**Comment by danieltabrizian** [comment]
Alright i was going to test that but when i use the library in my project it has allot of errors with @getter and @setter on eclipse mars

**Comment by thekeenant** [comment]
If you aren't using maven like it has in the readme, you are going to need to download the compiled jar file from ci.avicus.net

**Comment by thekeenant** [comment]
https://ci.avicus.net/job/Tabbed/lastSuccessfulBuild/artifact/target/tabbed-1.7-SNAPSHOT.jar

**Comment by danieltabrizian** [comment]
Does installing lomblok work?

**Comment by thekeenant** [comment]
Yes, but if you're doing it this way, you'll have to add protocollib to your project as well.

**Comment by thekeenant** [comment]
It's much easier just to download the jar and add it as a library to your plugin.

**Comment by danieltabrizian** [comment]
Alright i have done that, i still need to implement protocollib correct?

**Comment by thekeenant** [comment]
It will just need to be installed as a plugin on the server.

**Comment by danieltabrizian** [comment]
I got an issue using the .jar I have dropped it in my project folder and exported it after copying one of the examples, but it throws an noClassDefFoundError

**Comment by thekeenant** [comment]
And the jar is bundled inside your plugin? Provide the login this is the case.

**Comment by danieltabrizian** [comment]
How would i go about doing that?

**Comment by danieltabrizian** [comment]
Even when importing it like it is a plugin.jar/spigot.jar it throws that error.
It says it cant find Tabbed.class, In the tutorial you refrence it as tabbed without the capital T while it should be Tabbed.getTabbed(plugin) right?

**Comment by thekeenant** [comment]
Mhm it seems like the jar sources aren't being included in your plugin. I'd really advise using maven instead!

Otherwise I think this helps, though I don't use Eclipse: http://stackoverflow.com/questions/3280353/how-to-import-a-jar-in-eclipse

**Comment by danieltabrizian** [comment]
Alright so i switched to maven being sure its working as eclipse found the jar and it didnt give any errors but during execution the server still throws the following error:
`java.lang.NoClassDefFoundError: com/keenant/tabbed/Tabbed
        at solutions.elitedev.potionpvp.Tab.TabManager.createTab(TabManager.java:65) ~[?:?]
        at solutions.elitedev.potionpvp.Tab.TabManager$1.run(TabManager.java:41) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.ClassNotFoundException: com.keenant.tabbed.Tabbed
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_60]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
        ... 9 more`

**Comment by danieltabrizian** [comment]
Is there a difference between the documentation and the maven repository?
Because again the documentation says to stat with tabbed.newTableTabList(p);
While i found it to be Tabbed.getTabbed(plugin).newTableTabList(p);

**Comment by thekeenant** [comment]
You create a tabbed instance with `Tabbed tabbed = new Tabbed(plugin);` then can use `tabbed.newTableTabList(p)`. :+1:
